"""fixed the names 

Revision ID: 14d804d234d8
Revises: 58f0bfb8b27c
Create Date: 2025-12-28 10:11:12.541325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14d804d234d8"
down_revision: Union[str, Sequence[str], None] = "58f0bfb8b27c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Authors", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column("Authors", sa.Column("name", sa.String(), nullable=True))
    op.add_column("Authors", sa.Column("bio", sa.String(), nullable=True))
    op.drop_column("Authors", "Bio")
    op.drop_column("Authors", "Name")
    op.drop_column("Authors", "Id")
    op.add_column("Books", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column("Books", sa.Column("title", sa.String(), nullable=True))
    op.add_column("Books", sa.Column("isbn", sa.String(), nullable=True))
    op.add_column("Books", sa.Column("published_date", sa.DateTime(), nullable=True))
    op.add_column("Books", sa.Column("author_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("Books_AuthorId_fkey"), "Books", type_="foreignkey")
    op.create_foreign_key(
        None, "Books", "Authors", ["author_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("Books", "AuthorId")
    op.drop_column("Books", "ISBN")
    op.drop_column("Books", "PublishedDate")
    op.drop_column("Books", "Title")
    op.drop_column("Books", "Id")
    op.add_column("Borrowers", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column("Borrowers", sa.Column("name", sa.String(), nullable=True))
    op.add_column("Borrowers", sa.Column("email", sa.String(), nullable=True))
    op.add_column("Borrowers", sa.Column("phone", sa.String(), nullable=True))
    op.drop_constraint(op.f("Borrowers_Email_key"), "Borrowers", type_="unique")
    op.create_unique_constraint(None, "Borrowers", ["email"])
    op.drop_column("Borrowers", "Phone")
    op.drop_column("Borrowers", "Id")
    op.drop_column("Borrowers", "Name")
    op.drop_column("Borrowers", "Email")
    op.add_column("Loans", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column("Loans", sa.Column("book_id", sa.UUID(), nullable=True))
    op.add_column("Loans", sa.Column("borrower_id", sa.UUID(), nullable=True))
    op.add_column("Loans", sa.Column("loan_date", sa.DateTime(), nullable=True))
    op.add_column("Loans", sa.Column("return_date", sa.DateTime(), nullable=True))
    op.drop_constraint(op.f("Loans_BorrowerId_fkey"), "Loans", type_="foreignkey")
    op.drop_constraint(op.f("Loans_BookId_fkey"), "Loans", type_="foreignkey")
    op.create_foreign_key(
        None, "Loans", "Books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "Loans", "Borrowers", ["borrower_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("Loans", "ReturnDate")
    op.drop_column("Loans", "BorrowerId")
    op.drop_column("Loans", "BookId")
    op.drop_column("Loans", "LoanDate")
    op.drop_column("Loans", "Id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Loans", sa.Column("Id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "Loans",
        sa.Column(
            "LoanDate", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "Loans", sa.Column("BookId", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Loans", sa.Column("BorrowerId", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Loans",
        sa.Column(
            "ReturnDate", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "Loans", type_="foreignkey")
    op.drop_constraint(None, "Loans", type_="foreignkey")
    op.create_foreign_key(
        op.f("Loans_BookId_fkey"),
        "Loans",
        "Books",
        ["BookId"],
        ["Id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("Loans_BorrowerId_fkey"),
        "Loans",
        "Borrowers",
        ["BorrowerId"],
        ["Id"],
        ondelete="CASCADE",
    )
    op.drop_column("Loans", "return_date")
    op.drop_column("Loans", "loan_date")
    op.drop_column("Loans", "borrower_id")
    op.drop_column("Loans", "book_id")
    op.drop_column("Loans", "id")
    op.add_column(
        "Borrowers",
        sa.Column("Email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "Borrowers", sa.Column("Name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Borrowers", sa.Column("Id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "Borrowers",
        sa.Column("Phone", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "Borrowers", type_="unique")
    op.create_unique_constraint(
        op.f("Borrowers_Email_key"),
        "Borrowers",
        ["Email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("Borrowers", "phone")
    op.drop_column("Borrowers", "email")
    op.drop_column("Borrowers", "name")
    op.drop_column("Borrowers", "id")
    op.add_column(
        "Books", sa.Column("Id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "Books", sa.Column("Title", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Books",
        sa.Column("PublishedDate", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "Books", sa.Column("ISBN", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Books", sa.Column("AuthorId", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "Books", type_="foreignkey")
    op.create_foreign_key(
        op.f("Books_AuthorId_fkey"),
        "Books",
        "Authors",
        ["AuthorId"],
        ["Id"],
        ondelete="CASCADE",
    )
    op.drop_column("Books", "author_id")
    op.drop_column("Books", "published_date")
    op.drop_column("Books", "isbn")
    op.drop_column("Books", "title")
    op.drop_column("Books", "id")
    op.add_column(
        "Authors", sa.Column("Id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "Authors", sa.Column("Name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Authors", sa.Column("Bio", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("Authors", "bio")
    op.drop_column("Authors", "name")
    op.drop_column("Authors", "id")
    # ### end Alembic commands ###
